name: Build and Test

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/* 

      - run: npm i

      - name: Run tests
        run: npm test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - run: npm i

    - name: Get coverage
      run: npm run lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: './coverage/lcov.info'
