name: Build and Test

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/* 

      - run: npm i

      - name: Run tests
        run: npm test
